"""aggiunta colonna newsdata_id a tabella news

Revision ID: 178ff0c8c3a1
Revises: 3b5cae5f11f9
Create Date: 2026-09-22 11:36:19.585999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificatori della revisione usati da Alembic.
# Questi placeholder vengono sostituiti automaticamente quando crei una migration.
revision = '178ff0c8c3a1'
down_revision = '3b5cae5f11f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Codice applicato quando esegui `alembic upgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('newsdata_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Codice di rollback quando esegui `alembic downgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'newsdata_id')
    # ### end Alembic commands ###
