"""creata tabella notifications e notification_news

Revision ID: 3b5cae5f11f9
Revises: f3c542068da2
Create Date: 2026-09-16 10:45:12.575346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificatori della revisione usati da Alembic.
# Questi placeholder vengono sostituiti automaticamente quando crei una migration.
revision = '3b5cae5f11f9'
down_revision = 'f3c542068da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Codice applicato quando esegui `alembic upgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('notification_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_news_news_id'), 'notification_news', ['news_id'], unique=False)
    op.create_index(op.f('ix_notification_news_notification_id'), 'notification_news', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Codice di rollback quando esegui `alembic downgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_news_notification_id'), table_name='notification_news')
    op.drop_index(op.f('ix_notification_news_news_id'), table_name='notification_news')
    op.drop_table('notification_news')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
