"""aggiunta colonna relevance_user a tabella notification_news

Revision ID: c93100221884
Revises: f0fc29f92d9e
Create Date: 2026-10-07 18:40:07.736287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificatori della revisione usati da Alembic.
# Questi placeholder vengono sostituiti automaticamente quando crei una migration.
revision = 'c93100221884'
down_revision = 'f0fc29f92d9e'
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.add_column('notification_news', sa.Column('relevance_user', sa.Text(), nullable=True))

    op.execute("UPDATE notification_news SET relevance_user = '' WHERE relevance_user IS NULL")

    op.alter_column("notification_news", "relevance_user", nullable=False)


def downgrade() -> None:
    # Codice di rollback quando esegui `alembic downgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_news', 'relevance_user')
    # ### end Alembic commands ###
