"""aggiunta colonna notification_interval_days a tabella users

Revision ID: f0fc29f92d9e
Revises: 178ff0c8c3a1
Create Date: 2026-09-28 12:22:40.465050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificatori della revisione usati da Alembic.
# Questi placeholder vengono sostituiti automaticamente quando crei una migration.
revision = 'f0fc29f92d9e'
down_revision = '178ff0c8c3a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Codice applicato quando esegui `alembic upgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_interval_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Codice di rollback quando esegui `alembic downgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_interval_days')
    # ### end Alembic commands ###
