"""aggiunta colonna summary, link, source e language e modificata colonna created_at in date nella tabella news 

Revision ID: f3c542068da2
Revises: 20250101_000001
Create Date: 2026-09-15 16:12:19.630698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificatori della revisione usati da Alembic.
# Questi placeholder vengono sostituiti automaticamente quando crei una migration.
revision = 'f3c542068da2'
down_revision = '20250101_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Codice applicato quando esegui `alembic upgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('news', sa.Column('link', sa.String(length=500), nullable=False))
    op.add_column('news', sa.Column('source', sa.String(length=500), nullable=False))
    op.add_column('news', sa.Column('language', sa.String(length=500), nullable=False))
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('news', 'content_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'news', ['link'])
    op.drop_column('news', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Codice di rollback quando esegui `alembic downgrade`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='unique')
    op.alter_column('news', 'content_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('news', 'language')
    op.drop_column('news', 'source')
    op.drop_column('news', 'link')
    op.drop_column('news', 'date')
    op.drop_column('news', 'summary')
    # ### end Alembic commands ###
